version: '3.8'

services:
  twg-backend:
    container_name: twg-backend
    image: twg-backend
    build:
      context: ../
    env_file:
      - ../environment.env
    volumes:
      - type: bind
        source: ../resources/images #/home/twg/resources/images
        target: /home/twg/images
    ports:
      - "1337:1337"
    networks:
      - backend
      - database

networks:
  backend:
    name: backend_network
  database:
    name: database_network
    external: true