version: '3.8'

services:
  elk:
    image: sebp/elk
    ports:
      - 5601:5601 #kibana
      - 9200:9200 #elastic
      - 5044:5044 #logstash
    networks:
      - backend
      - monitoring:
        aliases:
        - elk

  grafana:
    build: './config/grafana'
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

    networks:
      - backend
      - monitoring:
        aliases:
        - grafana


  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - backend
      - frontend
      - monitoring:
        aliases:
        - prometheus
  
networks:
  backend:
    name: backend_network
    external: true
  frontend:
    name: frontend_network
    external: true
  monitoring:
    name: monitoring_network
